---
apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: nats-eventbus
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: nats