apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-js-disk
  namespace: nats-eventbus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi